# **Introdução ao Conceito de Árvore de Decisão**

Uma árvore de decisão é uma estrutura de modelagem não linear, que simula o processo de decisão com base em respostas a perguntas realizadas sequencialmente aos dados. Cada resposta é interpretada como um nó de divisão no algoritmo, e geometricamente representa uma divisão ortogonal a $n-1$ eixos das variáveis de saída.

Exemplo de uma estrutura de árvore de decisão:

<img src="https://i1.wp.com/www.vooo.pro/insights/wp-content/uploads/2016/12/RDS-Vooo_insights-Tutorial_arvore_de_decisao_02.jpg?resize=640%2C371&ssl=1" width=600>

A próxima imagem apresenta de forma ilustrativa o que acontece com o espaço de atributos.

<img src=https://paulvanderlaken.files.wordpress.com/2020/03/readme-titanic_plot-11.png width=500>

## **Processo de Aprendizado da Árvore de Decisão**

A primeira pergunta que uma árvore precisa responder é: *qual o atributo receberá a divisão?*

Dependendo do atributo que for utilizado no nó raiz, a árvore pode atingir um determinado grau de separação dos conjuntos de cada classe. Então deve existir uma métrica que direciona a separação para um determinado atributo.

<img src="https://i2.wp.com/www.vooo.pro/insights/wp-content/uploads/2016/12/RDS-Vooo-Tutorial_completo_arvore_decisao_03.jpg?resize=617%2C293&ssl=1" width=500>

### *Critério de Gini*

A impureza de Gini mede o quaõ "impuras" são as folhas de uma árvore contruídas após as divisões do nó. É calculada como:

$$Gini(D) = 1- \sum_{i=1}^{n}p_i$$

Essencialmente, a árvode de decisão compara a impureza de Gini antes e depois da realização das divisões em cada atributo, e seleciona aquele atributo que vai proporcionar a **maior purificação** da amostra.

### *Critério de Entropia*

A entropia é uma quantidade definida em física, engenharia e teoria da informação, com o objetivo de quantificar o **grau de desordem** de um sistema ou, de forma equivalente, o quanto se possui de informação a respeito de um sistema. É calculada como:

$$E = -\sum_{i=1}^{n}p_i \log_2{p_i}$$

De mesma forma, a árvore de decisão procura aquele atributo que proporciona a maior queda de entropia, que representa o maior ganho de informação.

In [ ]:
import warnings
import numpy as np
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, make_scorer
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV, StratifiedKFold

# ignorar warnings
warnings.filterwarnings('ignore')

In [ ]:
# montando drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
# definindo constantes
RANDOM_STATE = 18

In [ ]:
# caminho para o arquivo
PATH='/content/drive/MyDrive/Pos_Graduacao/FundamentosMachineLearning/data/german_credit.csv'
data = pd.read_csv(PATH)
data.head()

,Creditability,Account Balance,Duration of Credit (month),Payment Status of Previous Credit,Purpose,Credit Amount,Value Savings/Stocks,Length of current employment,Instalment per cent,Sex & Marital Status,...,Duration in Current address,Most valuable available asset,Age (years),Concurrent Credits,Type of apartment,No of Credits at this Bank,Occupation,No of dependents,Telephone,Foreign Worker
0,1,1,18,4,2,1049,1,2,4,2,...,4,2,21,3,1,1,3,1,1,1
1,1,1,9,4,0,2799,1,3,2,3,...,2,1,36,3,1,2,3,2,1,1
2,1,2,12,2,9,841,2,4,2,2,...,4,1,23,3,1,1,2,1,1,1
3,1,1,12,4,0,2122,1,3,3,3,...,2,1,39,3,1,2,2,2,1,2
4,1,1,12,4,0,2171,1,3,4,3,...,4,2,38,1,2,2,2,1,1,2

In [ ]:
# modificando os nomes das colunas
data.columns = data.columns.str.lower().str.replace(' ', '_')
data.head()

,creditability,account_balance,duration_of_credit_(month),payment_status_of_previous_credit,purpose,credit_amount,value_savings/stocks,length_of_current_employment,instalment_per_cent,sex_&_marital_status,...,duration_in_current_address,most_valuable_available_asset,age_(years),concurrent_credits,type_of_apartment,no_of_credits_at_this_bank,occupation,no_of_dependents,telephone,foreign_worker
0,1,1,18,4,2,1049,1,2,4,2,...,4,2,21,3,1,1,3,1,1,1
1,1,1,9,4,0,2799,1,3,2,3,...,2,1,36,3,1,2,3,2,1,1
2,1,2,12,2,9,841,2,4,2,2,...,4,1,23,3,1,1,2,1,1,1
3,1,1,12,4,0,2122,1,3,3,3,...,2,1,39,3,1,2,2,2,1,2
4,1,1,12,4,0,2171,1,3,4,3,...,4,2,38,1,2,2,2,1,1,2

In [ ]:
# separando x e y - vamos usar todos as colunas
x = data.drop(['creditability'], axis=1)
y = data[['creditability']]

In [ ]:
# separando treino e teste - com estratificação
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify=y)

In [ ]:
# treinando nossa primeira árvore de decisão - não precisa escalonamento
dt = DecisionTreeClassifier().fit(x_train, y_train)

# realizando novas previsões
yhat_train = dt.predict(x_train)
yhat_test = dt.predict(x_test)

In [ ]:
display(y.value_counts(normalize=True))

creditability
1                0.7
0                0.3
Name: proportion, dtype: float64

In [ ]:
# análise do desempenho
print('Desempenho - Base de Treino')
print(classification_report(y_train, yhat_train))

Desempenho - Base de Treino
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       210
           1       1.00      1.00      1.00       490

    accuracy                           1.00       700
   macro avg       1.00      1.00      1.00       700
weighted avg       1.00      1.00      1.00       700

Claramente houve um *overfitting* desse modelo. Ele foi capaz de modelar até os ruídos e variabilidades aleatórias do conjunto de dados, mas não foi capaz de reproduzir essas correlações no conjunto de teste.

Inevitavelmente, se fizermos perguntas o suficiente, vamos conseguir modelar qualquer sistema. No entanto, isso vai tornar o modelo tão complexo e específico, que dificilmente os padrões aprendidos serão reproduzidos em outros conjuntos de dados.

In [ ]:
# análise do desempenho
print('Desempenho - Base de Teste')
print(classification_report(y_test, yhat_test))

Desempenho - Base de Teste
              precision    recall  f1-score   support

           0       0.53      0.51      0.52        90
           1       0.79      0.80      0.80       210

    accuracy                           0.72       300
   macro avg       0.66      0.66      0.66       300
weighted avg       0.71      0.72      0.72       300

In [ ]:
# Analisando as dimensões da árvore criada
print(f'Profundidade da árvore: {dt.get_depth()}')
print(f'Número de folhas da árvore: {dt.get_n_leaves()}')

Profundidade da árvore: 15
Número de folhas da árvore: 141

In [ ]:
from sklearn.tree import export_graphviz
import graphviz

# Create a list of feature names with '&' replaced to avoid Graphviz errors
cleaned_feature_names = [col.replace('&', '_and_') for col in x_train.columns]

# Export the decision tree to a DOT file
dot_data = export_graphviz(dt, out_file=None,
                         feature_names=cleaned_feature_names,
                         class_names=['Good Credit', 'Bad Credit'],
                         filled=True, rounded=True,
                         special_characters=True)

In [ ]:
# Render the DOT graph
graph = graphviz.Source(dot_data)
graph.render('decision_tree_plot', view=True, format='png', cleanup=True)

'decision_tree_plot.png'

## **Determinação de Hiperparâmetros por Validação Cruzada**

Um dos desafios de se determinar os valores corretos de hiperparâmetros é que tais valores podem ser dependentes também dos dados que estamos submetendo o modelo. Não necessariamente um conjunto de hiperparâmetros que realizem uma boa previsão num conjunto de dados terá um bom desempenho em outro conjunto de dados.

Assim precisamos buscar um conjunto de hiperparâmetros que apresentem um bom desempenho *médio*, ou seja, que apresentem desempenhos adequados em diversas bases de dados distintas.

Para isso, podemos usar o conceito de **validação cruzada em $k$ folhas**. Veja um exemplo abaixo:

<img src="https://miro.medium.com/v2/resize:fit:720/format:webp/1*AAwIlHM8TpAVe4l2FihNUQ.png">

Na validação cruzada de $k$ folhas, o modelo é treinado $k$ vezes, sendo que em cada vez, uma fração de $1/k$ do conjunto de dados é utilizado como base de teste, enquanto as outras $(k-1)/k$ porções são utilizadas como base de treinamento.

Ao final do treinamento, escolhemos aquele conjunto de dados que resultam no melhor desempenho médio.

In [ ]:
# criando um pipeline de modelagem
pipe_dt = Pipeline([
    ('dt', DecisionTreeClassifier(random_state=RANDOM_STATE))
])

# configurar um espaço de busca
params_grid = {
    'dt__criterion': ['gini', 'entropy', 'log_loss'],
    'dt__max_depth': [2, 5, 10, 20]
}

# configurar um amostrador estratificado
splitter = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE)

# configurar o nosso "experimentador"
grid_search = GridSearchCV(
    estimator=pipe_dt,
    param_grid=params_grid,
    scoring='precision',
    cv=splitter,
    refit=True,
    verbose=10,
    error_score=0
)

In [ ]:
# realizando os experimentos
grid_search.fit(x_train, y_train)

Fitting 10 folds for each of 12 candidates, totalling 120 fits
[CV 1/10; 1/12] START dt__criterion=gini, dt__max_depth=2.......................
[CV 1/10; 1/12] END dt__criterion=gini, dt__max_depth=2;, score=0.765 total time=   0.0s
[CV 2/10; 1/12] START dt__criterion=gini, dt__max_depth=2.......................
[CV 2/10; 1/12] END dt__criterion=gini, dt__max_depth=2;, score=0.769 total time=   0.0s
[CV 3/10; 1/12] START dt__criterion=gini, dt__max_depth=2.......................
[CV 3/10; 1/12] END dt__criterion=gini, dt__max_depth=2;, score=0.800 total time=   0.0s
[CV 4/10; 1/12] START dt__criterion=gini, dt__max_depth=2.......................
[CV 4/10; 1/12] END dt__criterion=gini, dt__max_depth=2;, score=0.789 total time=   0.0s
[CV 5/10; 1/12] START dt__criterion=gini, dt__max_depth=2.......................
[CV 5/10; 1/12] END dt__criterion=gini, dt__max_depth=2;, score=0.793 total time=   0.0s
[CV 6/10; 1/12] START dt__criterion=gini, dt__max_depth=2.......................
[CV 6/10; 1/12] END dt__criterion=gini, dt__max_depth=2;, score=0.745 total time=   0.0s
[CV 7/10; 1/12] START dt__criterion=gini, dt__max_depth=2.......................
[CV 7/10; 1/12] END dt__criterion=gini, dt__max_depth=2;, score=0.725 total time=   0.0s
[CV 8/10; 1/12] START dt__criterion=gini, dt__max_depth=2.......................
[CV 8/10; 1/12] END dt__criterion=gini, dt__max_depth=2;, score=0.830 total time=   0.0s
[CV 9/10; 1/12] START dt__criterion=gini, dt__max_depth=2.......................
[CV 9/10; 1/12] END dt__criterion=gini, dt__max_depth=2;, score=0.737 total time=   0.0s
[CV 10/10; 1/12] START dt__criterion=gini, dt__max_depth=2......................
[CV 10/10; 1/12] END dt__criterion=gini, dt__max_depth=2;, score=0.738 total time=   0.0s
[CV 1/10; 2/12] START dt__criterion=gini, dt__max_depth=5.......................
[CV 1/10; 2/12] END dt__criterion=gini, dt__max_depth=5;, score=0.755 total time=   0.0s
[CV 2/10; 2/12] START dt__criterion=gini, dt__max_depth=5.......................
[CV 2/10; 2/12] END dt__criterion=gini, dt__max_depth=5;, score=0.778 total time=   0.1s
[CV 3/10; 2/12] START dt__criterion=gini, dt__max_depth=5.......................
[CV 3/10; 2/12] END dt__criterion=gini, dt__max_depth=5;, score=0.789 total time=   0.1s
[CV 4/10; 2/12] START dt__criterion=gini, dt__max_depth=5.......................
[CV 4/10; 2/12] END dt__criterion=gini, dt__max_depth=5;, score=0.759 total time=   0.0s
[CV 5/10; 2/12] START dt__criterion=gini, dt__max_depth=5.......................
[CV 5/10; 2/12] END dt__criterion=gini, dt__max_depth=5;, score=0.807 total time=   0.0s
[CV 6/10; 2/12] START dt__criterion=gini, dt__max_depth=5.......................
[CV 6/10; 2/12] END dt__criterion=gini, dt__max_depth=5;, score=0.776 total time=   0.0s
[CV 7/10; 2/12] START dt__criterion=gini, dt__max_depth=5.......................
[CV 7/10; 2/12] END dt__criterion=gini, dt__max_depth=5;, score=0.766 total time=   0.0s
[CV 8/10; 2/12] START dt__criterion=gini, dt__max_depth=5.......................
[CV 8/10; 2/12] END dt__criterion=gini, dt__max_depth=5;, score=0.774 total time=   0.0s
[CV 9/10; 2/12] START dt__criterion=gini, dt__max_depth=5.......................
[CV 9/10; 2/12] END dt__criterion=gini, dt__max_depth=5;, score=0.750 total time=   0.0s
[CV 10/10; 2/12] START dt__criterion=gini, dt__max_depth=5......................
[CV 10/10; 2/12] END dt__criterion=gini, dt__max_depth=5;, score=0.804 total time=   0.0s
[CV 1/10; 3/12] START dt__criterion=gini, dt__max_depth=10......................
[CV 1/10; 3/12] END dt__criterion=gini, dt__max_depth=10;, score=0.696 total time=   0.1s
[CV 2/10; 3/12] START dt__criterion=gini, dt__max_depth=10......................
[CV 2/10; 3/12] END dt__criterion=gini, dt__max_depth=10;, score=0.789 total time=   0.1s
[CV 3/10; 3/12] START dt__criterion=gini, dt__max_depth=10......................
[CV 3/10; 3/12] END dt__criterion=gini, dt__max_depth=10;, score=0.792 total time=   0.1s
[CV 4/10; 3/12] START dt__criterion=gini, dt__max_depth=10......................
[CV 4/10; 3/12] END dt__criterion=gini, dt__max_depth=10;, score=0.809 total time=   0.1s
[CV 5/10; 3/12] START dt__criterion=gini, dt__max_depth=10......................
[CV 5/10; 3/12] END dt__criterion=gini, dt__max_depth=10;, score=0.740 total time=   0.0s
[CV 6/10; 3/12] START dt__criterion=gini, dt__max_depth=10......................
[CV 6/10; 3/12] END dt__criterion=gini, dt__max_depth=10;, score=0.841 total time=   0.1s
[CV 7/10; 3/12] START dt__criterion=gini, dt__max_depth=10......................
[CV 7/10; 3/12] END dt__criterion=gini, dt__max_depth=10;, score=0.717 total time=   0.1s
[CV 8/10; 3/12] START dt__criterion=gini, dt__max_depth=10......................
[CV 8/10; 3/12] END dt__criterion=gini, dt__max_depth=10;, score=0.804 total time=   0.1s
[CV 9/10; 3/12] START dt__criterion=gini, dt__max_depth=10......................
[CV 9/10; 3/12] END dt__criterion=gini, dt__max_depth=10;, score=0.784 total time=   0.1s
[CV 10/10; 3/12] START dt__criterion=gini, dt__max_depth=10.....................
[CV 10/10; 3/12] END dt__criterion=gini, dt__max_depth=10;, score=0.792 total time=   0.1s
[CV 1/10; 4/12] START dt__criterion=gini, dt__max_depth=20......................
[CV 1/10; 4/12] END dt__criterion=gini, dt__max_depth=20;, score=0.739 total time=   0.1s
[CV 2/10; 4/12] START dt__criterion=gini, dt__max_depth=20......................
[CV 2/10; 4/12] END dt__criterion=gini, dt__max_depth=20;, score=0.796 total time=   0.1s
[CV 3/10; 4/12] START dt__criterion=gini, dt__max_depth=20......................
[CV 3/10; 4/12] END dt__criterion=gini, dt__max_depth=20;, score=0.766 total time=   0.0s
[CV 4/10; 4/12] START dt__criterion=gini, dt__max_depth=20......................
[CV 4/10; 4/12] END dt__criterion=gini, dt__max_depth=20;, score=0.739 total time=   0.0s
[CV 5/10; 4/12] START dt__criterion=gini, dt__max_depth=20......................
[CV 5/10; 4/12] END dt__criterion=gini, dt__max_depth=20;, score=0.773 total time=   0.1s
[CV 6/10; 4/12] START dt__criterion=gini, dt__max_depth=20......................
[CV 6/10; 4/12] END dt__criterion=gini, dt__max_depth=20;, score=0.867 total time=   0.1s
[CV 7/10; 4/12] START dt__criterion=gini, dt__max_depth=20......................
[CV 7/10; 4/12] END dt__criterion=gini, dt__max_depth=20;, score=0.700 total time=   0.1s
[CV 8/10; 4/12] START dt__criterion=gini, dt__max_depth=20......................
[CV 8/10; 4/12] END dt__criterion=gini, dt__max_depth=20;, score=0.804 total time=   0.0s
[CV 9/10; 4/12] START dt__criterion=gini, dt__max_depth=20......................
[CV 9/10; 4/12] END dt__criterion=gini, dt__max_depth=20;, score=0.769 total time=   0.0s
[CV 10/10; 4/12] START dt__criterion=gini, dt__max_depth=20.....................
[CV 10/10; 4/12] END dt__criterion=gini, dt__max_depth=20;, score=0.766 total time=   0.0s
[CV 1/10; 5/12] START dt__criterion=entropy, dt__max_depth=2....................
[CV 1/10; 5/12] END dt__criterion=entropy, dt__max_depth=2;, score=0.765 total time=   0.0s
[CV 2/10; 5/12] START dt__criterion=entropy, dt__max_depth=2....................
[CV 2/10; 5/12] END dt__criterion=entropy, dt__max_depth=2;, score=0.769 total time=   0.1s
[CV 3/10; 5/12] START dt__criterion=entropy, dt__max_depth=2....................
[CV 3/10; 5/12] END dt__criterion=entropy, dt__max_depth=2;, score=0.800 total time=   0.0s
[CV 4/10; 5/12] START dt__criterion=entropy, dt__max_depth=2....................
[CV 4/10; 5/12] END dt__criterion=entropy, dt__max_depth=2;, score=0.789 total time=   0.0s
[CV 5/10; 5/12] START dt__criterion=entropy, dt__max_depth=2....................
[CV 5/10; 5/12] END dt__criterion=entropy, dt__max_depth=2;, score=0.793 total time=   0.0s
[CV 6/10; 5/12] START dt__criterion=entropy, dt__max_depth=2....................
[CV 6/10; 5/12] END dt__criterion=entropy, dt__max_depth=2;, score=0.745 total time=   0.1s
[CV 7/10; 5/12] START dt__criterion=entropy, dt__max_depth=2....................
[CV 7/10; 5/12] END dt__criterion=entropy, dt__max_depth=2;, score=0.725 total time=   0.1s
[CV 8/10; 5/12] START dt__criterion=entropy, dt__max_depth=2....................
[CV 8/10; 5/12] END dt__criterion=entropy, dt__max_depth=2;, score=0.830 total time=   0.0s
[CV 9/10; 5/12] START dt__criterion=entropy, dt__max_depth=2....................
[CV 9/10; 5/12] END dt__criterion=entropy, dt__max_depth=2;, score=0.737 total time=   0.0s
[CV 10/10; 5/12] START dt__criterion=entropy, dt__max_depth=2...................
[CV 10/10; 5/12] END dt__criterion=entropy, dt__max_depth=2;, score=0.738 total time=   0.0s
[CV 1/10; 6/12] START dt__criterion=entropy, dt__max_depth=5....................
[CV 1/10; 6/12] END dt__criterion=entropy, dt__max_depth=5;, score=0.780 total time=   0.0s
[CV 2/10; 6/12] START dt__criterion=entropy, dt__max_depth=5....................
[CV 2/10; 6/12] END dt__criterion=entropy, dt__max_depth=5;, score=0.796 total time=   0.0s
[CV 3/10; 6/12] START dt__criterion=entropy, dt__max_depth=5....................
[CV 3/10; 6/12] END dt__criterion=entropy, dt__max_depth=5;, score=0.808 total time=   0.0s
[CV 4/10; 6/12] START dt__criterion=entropy, dt__max_depth=5....................
[CV 4/10; 6/12] END dt__criterion=entropy, dt__max_depth=5;, score=0.804 total time=   0.0s
[CV 5/10; 6/12] START dt__criterion=entropy, dt__max_depth=5....................
[CV 5/10; 6/12] END dt__criterion=entropy, dt__max_depth=5;, score=0.800 total time=   0.0s
[CV 6/10; 6/12] START dt__criterion=entropy, dt__max_depth=5....................
[CV 6/10; 6/12] END dt__criterion=entropy, dt__max_depth=5;, score=0.745 total time=   0.0s
[CV 7/10; 6/12] START dt__criterion=entropy, dt__max_depth=5....................
[CV 7/10; 6/12] END dt__criterion=entropy, dt__max_depth=5;, score=0.731 total time=   0.0s
[CV 8/10; 6/12] START dt__criterion=entropy, dt__max_depth=5....................
[CV 8/10; 6/12] END dt__criterion=entropy, dt__max_depth=5;, score=0.811 total time=   0.0s
[CV 9/10; 6/12] START dt__criterion=entropy, dt__max_depth=5....................
[CV 9/10; 6/12] END dt__criterion=entropy, dt__max_depth=5;, score=0.792 total time=   0.0s
[CV 10/10; 6/12] START dt__criterion=entropy, dt__max_depth=5...................
[CV 10/10; 6/12] END dt__criterion=entropy, dt__max_depth=5;, score=0.800 total time=   0.0s
[CV 1/10; 7/12] START dt__criterion=entropy, dt__max_depth=10...................
[CV 1/10; 7/12] END dt__criterion=entropy, dt__max_depth=10;, score=0.760 total time=   0.0s
[CV 2/10; 7/12] START dt__criterion=entropy, dt__max_depth=10...................
[CV 2/10; 7/12] END dt__criterion=entropy, dt__max_depth=10;, score=0.678 total time=   0.0s
[CV 3/10; 7/12] START dt__criterion=entropy, dt__max_depth=10...................
[CV 3/10; 7/12] END dt__criterion=entropy, dt__max_depth=10;, score=0.812 total time=   0.1s
[CV 4/10; 7/12] START dt__criterion=entropy, dt__max_depth=10...................
[CV 4/10; 7/12] END dt__criterion=entropy, dt__max_depth=10;, score=0.784 total time=   0.0s
[CV 5/10; 7/12] START dt__criterion=entropy, dt__max_depth=10...................
[CV 5/10; 7/12] END dt__criterion=entropy, dt__max_depth=10;, score=0.796 total time=   0.0s
[CV 6/10; 7/12] START dt__criterion=entropy, dt__max_depth=10...................
[CV 6/10; 7/12] END dt__criterion=entropy, dt__max_depth=10;, score=0.771 total time=   0.0s
[CV 7/10; 7/12] START dt__criterion=entropy, dt__max_depth=10...................
[CV 7/10; 7/12] END dt__criterion=entropy, dt__max_depth=10;, score=0.739 total time=   0.1s
[CV 8/10; 7/12] START dt__criterion=entropy, dt__max_depth=10...................
[CV 8/10; 7/12] END dt__criterion=entropy, dt__max_depth=10;, score=0.837 total time=   0.1s
[CV 9/10; 7/12] START dt__criterion=entropy, dt__max_depth=10...................
[CV 9/10; 7/12] END dt__criterion=entropy, dt__max_depth=10;, score=0.750 total time=   0.1s
[CV 10/10; 7/12] START dt__criterion=entropy, dt__max_depth=10..................
[CV 10/10; 7/12] END dt__criterion=entropy, dt__max_depth=10;, score=0.760 total time=   0.1s
[CV 1/10; 8/12] START dt__criterion=entropy, dt__max_depth=20...................
[CV 1/10; 8/12] END dt__criterion=entropy, dt__max_depth=20;, score=0.727 total time=   0.1s
[CV 2/10; 8/12] START dt__criterion=entropy, dt__max_depth=20...................
[CV 2/10; 8/12] END dt__criterion=entropy, dt__max_depth=20;, score=0.710 total time=   0.1s
[CV 3/10; 8/12] START dt__criterion=entropy, dt__max_depth=20...................
[CV 3/10; 8/12] END dt__criterion=entropy, dt__max_depth=20;, score=0.776 total time=   0.1s
[CV 4/10; 8/12] START dt__criterion=entropy, dt__max_depth=20...................
[CV 4/10; 8/12] END dt__criterion=entropy, dt__max_depth=20;, score=0.787 total time=   0.1s
[CV 5/10; 8/12] START dt__criterion=entropy, dt__max_depth=20...................
[CV 5/10; 8/12] END dt__criterion=entropy, dt__max_depth=20;, score=0.773 total time=   0.1s
[CV 6/10; 8/12] START dt__criterion=entropy, dt__max_depth=20...................
[CV 6/10; 8/12] END dt__criterion=entropy, dt__max_depth=20;, score=0.745 total time=   0.1s
[CV 7/10; 8/12] START dt__criterion=entropy, dt__max_depth=20...................
[CV 7/10; 8/12] END dt__criterion=entropy, dt__max_depth=20;, score=0.729 total time=   0.0s
[CV 8/10; 8/12] START dt__criterion=entropy, dt__max_depth=20...................
[CV 8/10; 8/12] END dt__criterion=entropy, dt__max_depth=20;, score=0.844 total time=   0.1s
[CV 9/10; 8/12] START dt__criterion=entropy, dt__max_depth=20...................
[CV 9/10; 8/12] END dt__criterion=entropy, dt__max_depth=20;, score=0.780 total time=   0.0s
[CV 10/10; 8/12] START dt__criterion=entropy, dt__max_depth=20..................
[CV 10/10; 8/12] END dt__criterion=entropy, dt__max_depth=20;, score=0.784 total time=   0.1s
[CV 1/10; 9/12] START dt__criterion=log_loss, dt__max_depth=2...................
[CV 1/10; 9/12] END dt__criterion=log_loss, dt__max_depth=2;, score=0.765 total time=   0.0s
[CV 2/10; 9/12] START dt__criterion=log_loss, dt__max_depth=2...................
[CV 2/10; 9/12] END dt__criterion=log_loss, dt__max_depth=2;, score=0.769 total time=   0.1s
[CV 3/10; 9/12] START dt__criterion=log_loss, dt__max_depth=2...................
[CV 3/10; 9/12] END dt__criterion=log_loss, dt__max_depth=2;, score=0.800 total time=   0.0s
[CV 4/10; 9/12] START dt__criterion=log_loss, dt__max_depth=2...................
[CV 4/10; 9/12] END dt__criterion=log_loss, dt__max_depth=2;, score=0.789 total time=   0.0s
[CV 5/10; 9/12] START dt__criterion=log_loss, dt__max_depth=2...................
[CV 5/10; 9/12] END dt__criterion=log_loss, dt__max_depth=2;, score=0.793 total time=   0.0s
[CV 6/10; 9/12] START dt__criterion=log_loss, dt__max_depth=2...................
[CV 6/10; 9/12] END dt__criterion=log_loss, dt__max_depth=2;, score=0.745 total time=   0.0s
[CV 7/10; 9/12] START dt__criterion=log_loss, dt__max_depth=2...................
[CV 7/10; 9/12] END dt__criterion=log_loss, dt__max_depth=2;, score=0.725 total time=   0.1s
[CV 8/10; 9/12] START dt__criterion=log_loss, dt__max_depth=2...................
[CV 8/10; 9/12] END dt__criterion=log_loss, dt__max_depth=2;, score=0.830 total time=   0.1s
[CV 9/10; 9/12] START dt__criterion=log_loss, dt__max_depth=2...................
[CV 9/10; 9/12] END dt__criterion=log_loss, dt__max_depth=2;, score=0.737 total time=   0.1s
[CV 10/10; 9/12] START dt__criterion=log_loss, dt__max_depth=2..................
[CV 10/10; 9/12] END dt__criterion=log_loss, dt__max_depth=2;, score=0.738 total time=   0.1s
[CV 1/10; 10/12] START dt__criterion=log_loss, dt__max_depth=5..................
[CV 1/10; 10/12] END dt__criterion=log_loss, dt__max_depth=5;, score=0.780 total time=   0.1s
[CV 2/10; 10/12] START dt__criterion=log_loss, dt__max_depth=5..................
[CV 2/10; 10/12] END dt__criterion=log_loss, dt__max_depth=5;, score=0.796 total time=   0.1s
[CV 3/10; 10/12] START dt__criterion=log_loss, dt__max_depth=5..................
[CV 3/10; 10/12] END dt__criterion=log_loss, dt__max_depth=5;, score=0.808 total time=   0.1s
[CV 4/10; 10/12] START dt__criterion=log_loss, dt__max_depth=5..................
[CV 4/10; 10/12] END dt__criterion=log_loss, dt__max_depth=5;, score=0.804 total time=   0.1s
[CV 5/10; 10/12] START dt__criterion=log_loss, dt__max_depth=5..................
[CV 5/10; 10/12] END dt__criterion=log_loss, dt__max_depth=5;, score=0.800 total time=   0.1s
[CV 6/10; 10/12] START dt__criterion=log_loss, dt__max_depth=5..................
[CV 6/10; 10/12] END dt__criterion=log_loss, dt__max_depth=5;, score=0.745 total time=   0.1s
[CV 7/10; 10/12] START dt__criterion=log_loss, dt__max_depth=5..................
[CV 7/10; 10/12] END dt__criterion=log_loss, dt__max_depth=5;, score=0.731 total time=   0.1s
[CV 8/10; 10/12] START dt__criterion=log_loss, dt__max_depth=5..................
[CV 8/10; 10/12] END dt__criterion=log_loss, dt__max_depth=5;, score=0.811 total time=   0.1s
[CV 9/10; 10/12] START dt__criterion=log_loss, dt__max_depth=5..................
[CV 9/10; 10/12] END dt__criterion=log_loss, dt__max_depth=5;, score=0.792 total time=   0.0s
[CV 10/10; 10/12] START dt__criterion=log_loss, dt__max_depth=5.................
[CV 10/10; 10/12] END dt__criterion=log_loss, dt__max_depth=5;, score=0.800 total time=   0.1s
[CV 1/10; 11/12] START dt__criterion=log_loss, dt__max_depth=10.................
[CV 1/10; 11/12] END dt__criterion=log_loss, dt__max_depth=10;, score=0.760 total time=   0.0s
[CV 2/10; 11/12] START dt__criterion=log_loss, dt__max_depth=10.................
[CV 2/10; 11/12] END dt__criterion=log_loss, dt__max_depth=10;, score=0.678 total time=   0.0s
[CV 3/10; 11/12] START dt__criterion=log_loss, dt__max_depth=10.................
[CV 3/10; 11/12] END dt__criterion=log_loss, dt__max_depth=10;, score=0.812 total time=   0.0s
[CV 4/10; 11/12] START dt__criterion=log_loss, dt__max_depth=10.................
[CV 4/10; 11/12] END dt__criterion=log_loss, dt__max_depth=10;, score=0.784 total time=   0.0s
[CV 5/10; 11/12] START dt__criterion=log_loss, dt__max_depth=10.................
[CV 5/10; 11/12] END dt__criterion=log_loss, dt__max_depth=10;, score=0.796 total time=   0.0s
[CV 6/10; 11/12] START dt__criterion=log_loss, dt__max_depth=10.................
[CV 6/10; 11/12] END dt__criterion=log_loss, dt__max_depth=10;, score=0.771 total time=   0.1s
[CV 7/10; 11/12] START dt__criterion=log_loss, dt__max_depth=10.................
[CV 7/10; 11/12] END dt__criterion=log_loss, dt__max_depth=10;, score=0.739 total time=   0.1s
[CV 8/10; 11/12] START dt__criterion=log_loss, dt__max_depth=10.................
[CV 8/10; 11/12] END dt__criterion=log_loss, dt__max_depth=10;, score=0.837 total time=   0.1s
[CV 9/10; 11/12] START dt__criterion=log_loss, dt__max_depth=10.................
[CV 9/10; 11/12] END dt__criterion=log_loss, dt__max_depth=10;, score=0.750 total time=   0.1s
[CV 10/10; 11/12] START dt__criterion=log_loss, dt__max_depth=10................
[CV 10/10; 11/12] END dt__criterion=log_loss, dt__max_depth=10;, score=0.760 total time=   0.0s
[CV 1/10; 12/12] START dt__criterion=log_loss, dt__max_depth=20.................
[CV 1/10; 12/12] END dt__criterion=log_loss, dt__max_depth=20;, score=0.727 total time=   0.1s
[CV 2/10; 12/12] START dt__criterion=log_loss, dt__max_depth=20.................
[CV 2/10; 12/12] END dt__criterion=log_loss, dt__max_depth=20;, score=0.710 total time=   0.1s
[CV 3/10; 12/12] START dt__criterion=log_loss, dt__max_depth=20.................
[CV 3/10; 12/12] END dt__criterion=log_loss, dt__max_depth=20;, score=0.776 total time=   0.1s
[CV 4/10; 12/12] START dt__criterion=log_loss, dt__max_depth=20.................
[CV 4/10; 12/12] END dt__criterion=log_loss, dt__max_depth=20;, score=0.787 total time=   0.0s
[CV 5/10; 12/12] START dt__criterion=log_loss, dt__max_depth=20.................
[CV 5/10; 12/12] END dt__criterion=log_loss, dt__max_depth=20;, score=0.773 total time=   0.1s

GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=18, shuffle=True),
             error_score=0,
             estimator=Pipeline(steps=[('dt',
                                        DecisionTreeClassifier(random_state=18))]),
             param_grid={'dt__criterion': ['gini', 'entropy', 'log_loss'],
                         'dt__max_depth': [2, 5, 10, 20]},
             scoring='precision', verbose=10)

In [ ]:
# analisar a melhor combinação de parâmetros
grid_search.best_params_

{'dt__criterion': 'entropy', 'dt__max_depth': 5}

In [ ]:
# qual foi o melhor desempenho médio?
grid_search.best_score_

np.float64(0.7866764863984621)

In [ ]:
# analisando a precisão de cada FOLD do melhor modelo
precision_cv = []
for i in range(10):
  precision_fold = grid_search.cv_results_[f'split{i}_test_score'][
      np.where(grid_search.cv_results_['rank_test_score']==1)
  ][0]
  precision_cv.append(precision_fold)

print('Vetor de Precisões:', precision_cv)
print('Desvio Padrão:', np.std(precision_cv))
print('Coeficiente de Variação:', np.std(precision_cv) * 100 / np.mean(precision_cv))
print('95 % CI:', np.mean(precision_cv) - 1.96 * np.std(precision_cv)/np.sqrt(10), np.mean(precision_cv) + 1.96 * np.std(precision_cv)/np.sqrt(10))

Vetor de Precisões: [np.float64(0.78), np.float64(0.7962962962962963), np.float64(0.8076923076923077), np.float64(0.803921568627451), np.float64(0.8), np.float64(0.7450980392156863), np.float64(0.7307692307692307), np.float64(0.8113207547169812), np.float64(0.7916666666666666), np.float64(0.8)]
Desvio Padrão: 0.025918788957833148
Coeficiente de Variação: 3.294720181162875
95 % CI: 0.7706118545676671 0.8027411182292571

In [ ]:
# analisar o desempenho final
yhat_train = grid_search.best_estimator_.predict(x_train)
yhat_test = grid_search.best_estimator_.predict(x_test)

# análise das métricas
print('Desempenho - Base de Treino')
print(classification_report(y_train, yhat_train))

# análise do desempenho
print('Desempenho - Base de Teste')
print(classification_report(y_test, yhat_test))

Desempenho - Base de Treino
              precision    recall  f1-score   support

           0       0.66      0.61      0.64       210
           1       0.84      0.87      0.85       490

    accuracy                           0.79       700
   macro avg       0.75      0.74      0.75       700
weighted avg       0.79      0.79      0.79       700

Desempenho - Base de Teste
              precision    recall  f1-score   support

           0       0.54      0.54      0.54        90
           1       0.80      0.80      0.80       210

    accuracy                           0.73       300
   macro avg       0.67      0.67      0.67       300
weighted avg       0.73      0.73      0.73       300

In [ ]:
# criando um pipeline de modelagem
pipe_dt_bigger = Pipeline([
    ('dt', DecisionTreeClassifier(random_state=RANDOM_STATE))
])

# configurar um espaço de busca
params_grid = {
    'dt__criterion': ['gini', 'entropy', 'log_loss'],
    'dt__max_depth': range(2, 51),
    'dt__splitter': ['best', 'random'],
    'dt__class_weight': [None, 'balanced']

}

# configurar um amostrador estratificado
splitter = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE)

# configurar o nosso "experimentador"
random_search = RandomizedSearchCV(
    estimator=pipe_dt_bigger,
    param_distributions=params_grid,
    scoring='precision',
    n_iter=200,
    cv=splitter,
    refit=True,
    verbose=10,
    error_score=0,
    random_state=RANDOM_STATE
)

In [ ]:
# realizando os experimentos
random_search.fit(x_train, y_train)

Fitting 10 folds for each of 200 candidates, totalling 2000 fits
[CV 1/10; 1/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random
[CV 1/10; 1/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random;, score=0.729 total time=   0.0s
[CV 2/10; 1/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random
[CV 2/10; 1/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random;, score=0.784 total time=   0.0s
[CV 3/10; 1/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random
[CV 3/10; 1/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random;, score=0.787 total time=   0.0s
[CV 4/10; 1/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random
[CV 4/10; 1/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random;, score=0.787 total time=   0.0s
[CV 5/10; 1/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random
[CV 5/10; 1/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random;, score=0.735 total time=   0.0s
[CV 6/10; 1/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random
[CV 6/10; 1/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random;, score=0.776 total time=   0.0s
[CV 7/10; 1/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random
[CV 7/10; 1/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random;, score=0.783 total time=   0.0s
[CV 8/10; 1/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random
[CV 8/10; 1/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random;, score=0.850 total time=   0.0s
[CV 9/10; 1/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random
[CV 9/10; 1/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random;, score=0.694 total time=   0.0s
[CV 10/10; 1/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random
[CV 10/10; 1/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=21, dt__splitter=random;, score=0.745 total time=   0.0s
[CV 1/10; 2/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best
[CV 1/10; 2/200] END dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best;, score=0.776 total time=   0.0s
[CV 2/10; 2/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best
[CV 2/10; 2/200] END dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best;, score=0.759 total time=   0.0s
[CV 3/10; 2/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best
[CV 3/10; 2/200] END dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best;, score=0.870 total time=   0.0s
[CV 4/10; 2/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best
[CV 4/10; 2/200] END dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best;, score=0.788 total time=   0.0s
[CV 5/10; 2/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best
[CV 5/10; 2/200] END dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best;, score=0.868 total time=   0.0s
[CV 6/10; 2/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best
[CV 6/10; 2/200] END dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best;, score=0.767 total time=   0.0s
[CV 7/10; 2/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best
[CV 7/10; 2/200] END dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best;, score=0.778 total time=   0.0s
[CV 8/10; 2/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best
[CV 8/10; 2/200] END dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best;, score=0.903 total time=   0.0s
[CV 9/10; 2/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best
[CV 9/10; 2/200] END dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best;, score=0.756 total time=   0.0s
[CV 10/10; 2/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best
[CV 10/10; 2/200] END dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=6, dt__splitter=best;, score=0.812 total time=   0.0s
[CV 1/10; 3/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best
[CV 1/10; 3/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best;, score=0.739 total time=   0.0s
[CV 2/10; 3/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best
[CV 2/10; 3/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best;, score=0.796 total time=   0.0s
[CV 3/10; 3/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best
[CV 3/10; 3/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best;, score=0.766 total time=   0.0s
[CV 4/10; 3/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best
[CV 4/10; 3/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best;, score=0.739 total time=   0.0s
[CV 5/10; 3/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best
[CV 5/10; 3/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best;, score=0.773 total time=   0.0s
[CV 6/10; 3/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best
[CV 6/10; 3/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best;, score=0.867 total time=   0.0s
[CV 7/10; 3/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best
[CV 7/10; 3/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best;, score=0.700 total time=   0.0s
[CV 8/10; 3/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best
[CV 8/10; 3/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best;, score=0.804 total time=   0.0s
[CV 9/10; 3/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best
[CV 9/10; 3/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best;, score=0.769 total time=   0.0s
[CV 10/10; 3/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best
[CV 10/10; 3/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=21, dt__splitter=best;, score=0.766 total time=   0.0s
[CV 1/10; 4/200] START dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best
[CV 1/10; 4/200] END dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best;, score=0.759 total time=   0.0s
[CV 2/10; 4/200] START dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best
[CV 2/10; 4/200] END dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best;, score=0.745 total time=   0.0s
[CV 3/10; 4/200] START dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best
[CV 3/10; 4/200] END dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best;, score=0.812 total time=   0.0s
[CV 4/10; 4/200] START dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best
[CV 4/10; 4/200] END dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best;, score=0.780 total time=   0.0s
[CV 5/10; 4/200] START dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best
[CV 5/10; 4/200] END dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best;, score=0.822 total time=   0.0s
[CV 6/10; 4/200] START dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best
[CV 6/10; 4/200] END dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best;, score=0.774 total time=   0.0s
[CV 7/10; 4/200] START dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best
[CV 7/10; 4/200] END dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best;, score=0.717 total time=   0.0s
[CV 8/10; 4/200] START dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best
[CV 8/10; 4/200] END dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best;, score=0.825 total time=   0.0s
[CV 9/10; 4/200] START dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best
[CV 9/10; 4/200] END dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best;, score=0.729 total time=   0.0s
[CV 10/10; 4/200] START dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best
[CV 10/10; 4/200] END dt__class_weight=balanced, dt__criterion=log_loss, dt__max_depth=48, dt__splitter=best;, score=0.837 total time=   0.0s
[CV 1/10; 5/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best
[CV 1/10; 5/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best;, score=0.765 total time=   0.0s
[CV 2/10; 5/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best
[CV 2/10; 5/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best;, score=0.769 total time=   0.0s
[CV 3/10; 5/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best
[CV 3/10; 5/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best;, score=0.800 total time=   0.0s
[CV 4/10; 5/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best
[CV 4/10; 5/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best;, score=0.789 total time=   0.0s
[CV 5/10; 5/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best
[CV 5/10; 5/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best;, score=0.793 total time=   0.0s
[CV 6/10; 5/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best
[CV 6/10; 5/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best;, score=0.745 total time=   0.0s
[CV 7/10; 5/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best
[CV 7/10; 5/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best;, score=0.725 total time=   0.1s
[CV 8/10; 5/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best
[CV 8/10; 5/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best;, score=0.830 total time=   0.1s
[CV 9/10; 5/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best
[CV 9/10; 5/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best;, score=0.737 total time=   0.1s
[CV 10/10; 5/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best
[CV 10/10; 5/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=2, dt__splitter=best;, score=0.738 total time=   0.1s
[CV 1/10; 6/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best
[CV 1/10; 6/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best;, score=0.727 total time=   0.1s
[CV 2/10; 6/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best
[CV 2/10; 6/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best;, score=0.710 total time=   0.1s
[CV 3/10; 6/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best
[CV 3/10; 6/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best;, score=0.776 total time=   0.1s
[CV 4/10; 6/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best
[CV 4/10; 6/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best;, score=0.787 total time=   0.0s
[CV 5/10; 6/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best
[CV 5/10; 6/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best;, score=0.773 total time=   0.0s
[CV 6/10; 6/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best
[CV 6/10; 6/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best;, score=0.745 total time=   0.0s
[CV 7/10; 6/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best
[CV 7/10; 6/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best;, score=0.729 total time=   0.0s
[CV 8/10; 6/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best
[CV 8/10; 6/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best;, score=0.844 total time=   0.0s
[CV 9/10; 6/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best
[CV 9/10; 6/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best;, score=0.780 total time=   0.0s
[CV 10/10; 6/200] START dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best
[CV 10/10; 6/200] END dt__class_weight=None, dt__criterion=log_loss, dt__max_depth=26, dt__splitter=best;, score=0.784 total time=   0.0s
[CV 1/10; 7/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random
[CV 1/10; 7/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random;, score=0.746 total time=   0.0s
[CV 2/10; 7/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random
[CV 2/10; 7/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random;, score=0.716 total time=   0.0s
[CV 3/10; 7/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random
[CV 3/10; 7/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random;, score=0.754 total time=   0.0s
[CV 4/10; 7/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random
[CV 4/10; 7/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random;, score=0.723 total time=   0.0s
[CV 5/10; 7/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random
[CV 5/10; 7/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random;, score=0.721 total time=   0.0s
[CV 6/10; 7/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random
[CV 6/10; 7/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random;, score=0.701 total time=   0.0s
[CV 7/10; 7/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random
[CV 7/10; 7/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random;, score=0.687 total time=   0.0s
[CV 8/10; 7/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random
[CV 8/10; 7/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random;, score=0.786 total time=   0.0s
[CV 9/10; 7/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random
[CV 9/10; 7/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random;, score=0.741 total time=   0.0s
[CV 10/10; 7/200] START dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random
[CV 10/10; 7/200] END dt__class_weight=None, dt__criterion=gini, dt__max_depth=3, dt__splitter=random;, score=0.708 total time=   0.0s
[CV 1/10; 8/200] START dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best
[CV 1/10; 8/200] END dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best;, score=0.727 total time=   0.0s
[CV 2/10; 8/200] START dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best
[CV 2/10; 8/200] END dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best;, score=0.710 total time=   0.0s
[CV 3/10; 8/200] START dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best
[CV 3/10; 8/200] END dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best;, score=0.776 total time=   0.0s
[CV 4/10; 8/200] START dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best
[CV 4/10; 8/200] END dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best;, score=0.787 total time=   0.0s
[CV 5/10; 8/200] START dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best
[CV 5/10; 8/200] END dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best;, score=0.773 total time=   0.0s
[CV 6/10; 8/200] START dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best
[CV 6/10; 8/200] END dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best;, score=0.745 total time=   0.0s
[CV 7/10; 8/200] START dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best
[CV 7/10; 8/200] END dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best;, score=0.729 total time=   0.0s
[CV 8/10; 8/200] START dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best
[CV 8/10; 8/200] END dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best;, score=0.844 total time=   0.0s
[CV 9/10; 8/200] START dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best
[CV 9/10; 8/200] END dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best;, score=0.780 total time=   0.0s
[CV 10/10; 8/200] START dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best
[CV 10/10; 8/200] END dt__class_weight=None, dt__criterion=entropy, dt__max_depth=44, dt__splitter=best;, score=0.784 total time=   0.0s
[CV 1/10; 9/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=21, dt__splitter=random
[CV 1/10; 9/200] END dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=21, dt__splitter=random;, score=0.741 total time=   0.0s
[CV 2/10; 9/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=21, dt__splitter=random
[CV 2/10; 9/200] END dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=21, dt__splitter=random;, score=0.712 total time=   0.0s
[CV 3/10; 9/200] START dt__class_weight=balanced, dt__criterion=gini, dt__max_depth=21, dt__splitter=random

RandomizedSearchCV(cv=StratifiedKFold(n_splits=10, random_state=18, shuffle=True),
                   error_score=0,
                   estimator=Pipeline(steps=[('dt',
                                              DecisionTreeClassifier(random_state=18))]),
                   n_iter=200,
                   param_distributions={'dt__class_weight': [None, 'balanced'],
                                        'dt__criterion': ['gini', 'entropy',
                                                          'log_loss'],
                                        'dt__max_depth': range(2, 51),
                                        'dt__splitter': ['best', 'random']},
                   random_state=18, scoring='precision', verbose=10)

In [ ]:
# realizando os experimentos
random_search.fit(x_train, y_train)

{'dt__splitter': 'random',
 'dt__max_depth': 2,
 'dt__criterion': 'gini',
 'dt__class_weight': 'balanced'}

In [ ]:
# qual foi o melhor desempenho médio?
random_search.best_score_

np.float64(0.8498918559754471)

In [ ]:
# analisando a precisão de cada FOLD do melhor modelo
precision_cv = []
for i in range(10):
  precision_fold = random_search.cv_results_[f'split{i}_test_score'][
      np.where(random_search.cv_results_['rank_test_score']==1)
  ][0]
  precision_cv.append(precision_fold)

print('Vetor de Precisões:', precision_cv)
print('Desvio Padrão:', np.std(precision_cv))
print('Coeficiente de Variação:', np.std(precision_cv) * 100 / np.mean(precision_cv))
print('95 % CI:', np.mean(precision_cv) - 1.96 * np.std(precision_cv)/np.sqrt(10), np.mean(precision_cv) + 1.96 * np.std(precision_cv)/np.sqrt(10))

Vetor de Precisões: [np.float64(0.875), np.float64(0.8918918918918919), np.float64(0.8157894736842105), np.float64(0.8285714285714286), np.float64(0.8717948717948718), np.float64(0.8181818181818182), np.float64(0.7941176470588235), np.float64(0.9285714285714286), np.float64(0.8), np.float64(0.875)]
Desvio Padrão: 0.042329749973300454
Coeficiente de Variação: 4.980604258728576
95 % CI: 0.8236556051260353 0.876128106824859

In [ ]:
# analisar o desempenho final
yhat_train = random_search.best_estimator_.predict(x_train)
yhat_test = random_search.best_estimator_.predict(x_test)

# análise das métricas
print('Desempenho - Base de Treino')
print(classification_report(y_train, yhat_train))

# análise do desempenho
print('Desempenho - Base de Teste')
print(classification_report(y_test, yhat_test))

Desempenho - Base de Treino
              precision    recall  f1-score   support

           0       0.47      0.76      0.58       210
           1       0.86      0.63      0.73       490

    accuracy                           0.67       700
   macro avg       0.66      0.69      0.65       700
weighted avg       0.74      0.67      0.68       700

Desempenho - Base de Teste
              precision    recall  f1-score   support

           0       0.45      0.80      0.58        90
           1       0.87      0.59      0.70       210

    accuracy                           0.65       300
   macro avg       0.66      0.69      0.64       300
weighted avg       0.75      0.65      0.66       300

In [ ]:
random_search.cv_results_['rank_test_score']

array([133,  10,  97,  36, 117, 140, 199, 140,  52, 198,  69,  36,  25,
        30, 169, 169,  97, 140,  36,  51,  63,  22,  52,  29,   7, 191,
        17,  34,  69,  36,  69,  14, 122,  52, 122, 140,   9, 108,  36,
        69, 196,  36,  69,  18,   6,  69,  36, 140,  97, 168,  28,   7,
       169, 140, 140, 169, 140, 190, 139, 140, 189,  12,  97,  52,  27,
       137,  20, 116,  94,  35,  66, 140, 192, 169, 140, 140,  31, 140,
        36,  36,  69,  69,  32,  97, 140,  16,  64, 169, 108,  36, 140,
        13, 169,  69, 169,  52, 122,  52, 120, 140,  69,  65, 140,  69,
        69, 108,  97, 140,  69, 169, 122,  36, 140,  25,  23, 121,  69,
       169, 169,   2,  94,  97, 140, 108,  24, 195, 169,  69, 169,  36,
        97, 169, 108,  67,  69,  36, 169, 108,  69,  97, 140, 169, 122,
        69, 194, 192, 140,  21, 122, 117, 122,   5, 133,  52,  11,  69,
       117, 122, 122,  69,  36,  36,  62,  69, 135,  33, 200, 140,  69,
         4,  67, 140, 197, 140,   3, 169, 169,  96, 136, 167,  61, 108,
       140, 122,   1,  97,  15, 169, 122,  52,  69,  69,  52,  19, 108,
        97, 138,  69, 188, 140], dtype=int32)